# Generated by Django 5.1.7 on 2025-03-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
